name: Unzip tiles

on:
  push:
    paths:
      - 'tiles.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip
        run: |
          mkdir -p tiles
          unzip -o tiles.zip -d tiles/
          rm tiles.zip

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add tiles/
          git commit -m "Unpacked tiles.zip" || echo "Nothing to commit"
          git push
